variable "enabled" {
  description = "Set to false to prevent the module from creating any resources"
  type        = bool
  default     = true
}

variable "location" {
  description = "The Azure Region where the App Service Plan should be created"
  type        = string
}

variable "resource_group_name" {
  description = "The name of the resource group in which to create the App Service Plan"
  type        = string
}

variable "app_service_plan_name" {
  description = "Custom name for the App Service Plan. If not specified, the module will use the ID from the label module"
  type        = string
  default     = null
}

variable "os_type" {
  description = "The O/S type for the App Service Plan. Possible values are Linux and Windows"
  type        = string
  default     = "Linux"

  validation {
    condition     = contains(["Linux", "Windows"], var.os_type)
    error_message = "The os_type must be either Linux or Windows."
  }
}

variable "sku_name" {
  description = "The SKU for the App Service Plan. Possible values include B1, B2, B3, D1, F1, FREE, I1, I2, I3, I1v2, I2v2, I3v2, P1v2, P2v2, P3v2, P0v3, P1v3, P1mv3, P2v3, P2mv3, P3v3, P3mv3, P4mv3, P5mv3, S1, S2, S3, SHARED, Y1, EP1, EP2, EP3, WS1, WS2, WS3"
  type        = string
  default     = "B1"
}

variable "worker_count" {
  description = "The number of Workers (instances) to be allocated"
  type        = number
  default     = 1
}

variable "per_site_scaling_enabled" {
  description = "Should Per Site Scaling be enabled"
  type        = bool
  default     = false
}

variable "zone_balancing_enabled" {
  description = "Should the Service Plan balance across Availability Zones in the region"
  type        = bool
  default     = false
}

# =============================================================================
# Cloudposse Label Variables
# =============================================================================

variable "namespace" {
  description = "ID element. Usually an abbreviation of your organization name, e.g. 'eg' or 'cp', to help ensure generated IDs are globally unique"
  type        = string
  default     = null
}

variable "tenant" {
  description = "ID element _(Rarely used, not included by default)_. A customer identifier, indicating who this instance of a resource is for"
  type        = string
  default     = null
}

variable "environment" {
  description = "ID element. Usually used for region e.g. 'uw2', 'us-west-2', OR role 'prod', 'staging', 'dev', 'UAT'"
  type        = string
  default     = null
}

variable "stage" {
  description = "ID element. Usually used to indicate role, e.g. 'prod', 'staging', 'source', 'build', 'test', 'deploy', 'release'"
  type        = string
  default     = null
}

variable "name" {
  description = "ID element. Usually the component or solution name, e.g. 'app' or 'jenkins'"
  type        = string
  default     = null
}

variable "attributes" {
  description = "ID element. Additional attributes (e.g. `workers` or `cluster`) to add to `id`, in the order they appear in the list. New attributes are appended to the end of the list. The elements of the list are joined by the `delimiter` and treated as a single ID element."
  type        = list(string)
  default     = []
}

variable "delimiter" {
  description = "Delimiter to be used between ID elements. Defaults to - (hyphen). Set to empty string to use no delimiter at all."
  type        = string
  default     = null
}

variable "tags" {
  description = "Additional tags (e.g. {'BusinessUnit': 'XYZ'}). Neither the tag keys nor the tag values will be modified by this module."
  type        = map(string)
  default     = {}
}

variable "regex_replace_chars" {
  description = "Terraform regular expression (regex) string. Characters matching the regex will be removed from the ID elements. If not set, /[^a-zA-Z0-9-]/ is used to remove all characters other than hyphens, letters and digits."
  type        = string
  default     = null
}

variable "label_order" {
  description = "The order in which the labels (ID elements) appear in the id. Defaults to [namespace, environment, stage, name, attributes]. You can omit any of the 6 labels (tenant is the 6th), but at least one must be present."
  type        = list(string)
  default     = null
}

variable "label_key_case" {
  description = "Controls the letter case of the tags keys (label names) for tags generated by this module. Does not affect keys of tags passed in via the tags input. Possible values: lower, title, upper. Default value: title."
  type        = string
  default     = null
}

variable "label_value_case" {
  description = "Controls the letter case of ID elements (labels) as included in id, set as tag values, and output by this module individually. Does not affect values of tags passed in via the tags input. Possible values: lower, title, upper and none (no transformation). Set this to title and set delimiter to empty string to yield Pascal Case IDs. Default value: lower."
  type        = string
  default     = null
}

variable "id_length_limit" {
  description = "Limit id to this many characters (minimum 6). Set to 0 for unlimited length. Set to null for keep the existing setting, which defaults to 0. Does not affect id_full."
  type        = number
  default     = null
}