components:
  terraform:
    azure-nsg:
      vars:
        # Production environment with strict security rules
        custom_security_rules:
          AllowHTTPS:
            priority: 100
            direction: "Inbound"
            access: "Allow"
            protocol: "Tcp"
            source_port_range: "*"
            destination_port_range: "443"
            source_address_prefix: "*"
            destination_address_prefix: "*"
          
          AllowLoadBalancer:
            priority: 101
            direction: "Inbound"
            access: "Allow"
            protocol: "Tcp"
            source_port_range: "*"
            destination_port_ranges: ["80", "443"]
            source_address_prefix: "AzureLoadBalancer"
            destination_address_prefix: "*"
          
          DenyAllOther:
            priority: 4000
            direction: "Inbound"
            access: "Deny"
            protocol: "*"
            source_port_range: "*"
            destination_port_range: "*"
            source_address_prefix: "*"
            destination_address_prefix: "*"