import:
  - orgs/lazylabs/_defaults
  - catalog/azure-rsg/defaults
  - catalog/azure-rsg/mixins/dev
  - catalog/azure-vnet/defaults
  - catalog/azure-vnet/mixins/dev
  - catalog/azure-subnet/defaults
  - catalog/azure-subnet/mixins/dev
  - catalog/azure-private-endpoint/defaults
  - catalog/azure-private-endpoint/mixins/dev
  - catalog/azure-storage-account/defaults
  - catalog/azure-storage-account/mixins/dev

vars:
  environment: "eus"
  stage: "dev"
  location: "East US"

components:
  terraform:
    azure-resource-group:
      vars:
        name: "services"
        attributes: ["shared"]

    azure-vnet:
      vars:
        name: "network"
        address_space: ["10.0.0.0/16"]
        dns_servers: ["168.63.129.16"]
        # Reference the resource group component's variables
        resource_group_name: "${var.environment}${var.stage}${components.terraform.azure-resource-group.vars.name}${var.namespace}"

    azure-subnet:
      vars:
        name: "web"
        address_prefixes: ["10.0.1.0/24"]
        # Reference the resource group and vnet components
        resource_group_name: "${var.environment}${var.stage}${components.terraform.azure-resource-group.vars.name}${var.namespace}"
        virtual_network_name: "${var.environment}${var.stage}${components.terraform.azure-vnet.vars.name}${var.namespace}"
        # Enable private endpoint network policies
        private_endpoint_network_policies: "Enabled"

    # Multiple Private Endpoint Examples - Different Services with Different Configurations
    
    # Example 1: Storage Account Private Endpoint for Blob Service
    # azure-private-endpoint-storage-blob:
    #   metadata:
    #     component: azure-private-endpoint
    #   vars:
    #     name: "stgblob"
    #     attributes: ["blob"]
    #     location: "${var.location}"
    #     resource_group_name: "${var.environment}${var.stage}${components.terraform.azure-resource-group.vars.name}${var.namespace}"
    #     subnet_id: "/subscriptions/{subscription-id}/resourceGroups/${var.environment}${var.stage}${components.terraform.azure-resource-group.vars.name}${var.namespace}/providers/Microsoft.Network/virtualNetworks/${var.environment}${var.stage}${components.terraform.azure-vnet.vars.name}${var.namespace}/subnets/${var.environment}${var.stage}${components.terraform.azure-subnet.vars.name}${var.namespace}"
    #     private_connection_resource_id: "/subscriptions/{subscription-id}/resourceGroups/{rg}/providers/Microsoft.Storage/storageAccounts/{storage-account-name}"
    #     subresource_names: ["blob"]
    #     private_dns_zone_group:
    #       name: "storage-blob-dns-zone-group"
    #       private_dns_zone_ids: ["/subscriptions/{subscription-id}/resourceGroups/{dns-rg}/providers/Microsoft.Network/privateDnsZones/privatelink.blob.core.windows.net"]

    # Example 2: Storage Account Private Endpoint for File Service (same storage, different subresource)
    # azure-private-endpoint-storage-file:
    #   metadata:
    #     component: azure-private-endpoint
    #   vars:
    #     name: "stgfile"
    #     attributes: ["file"]
    #     location: "${var.location}"
    #     resource_group_name: "${var.environment}${var.stage}${components.terraform.azure-resource-group.vars.name}${var.namespace}"
    #     subnet_id: "/subscriptions/{subscription-id}/resourceGroups/${var.environment}${var.stage}${components.terraform.azure-resource-group.vars.name}${var.namespace}/providers/Microsoft.Network/virtualNetworks/${var.environment}${var.stage}${components.terraform.azure-vnet.vars.name}${var.namespace}/subnets/${var.environment}${var.stage}${components.terraform.azure-subnet.vars.name}${var.namespace}"
    #     private_connection_resource_id: "/subscriptions/{subscription-id}/resourceGroups/{rg}/providers/Microsoft.Storage/storageAccounts/{storage-account-name}"
    #     subresource_names: ["file"]
    #     private_dns_zone_group:
    #       name: "storage-file-dns-zone-group"
    #       private_dns_zone_ids: ["/subscriptions/{subscription-id}/resourceGroups/{dns-rg}/providers/Microsoft.Network/privateDnsZones/privatelink.file.core.windows.net"]

    # Example 3: Key Vault Private Endpoint
    # azure-private-endpoint-keyvault:
    #   metadata:
    #     component: azure-private-endpoint
    #   vars:
    #     name: "keyvault"
    #     location: "${var.location}"
    #     resource_group_name: "${var.environment}${var.stage}${components.terraform.azure-resource-group.vars.name}${var.namespace}"
    #     subnet_id: "/subscriptions/{subscription-id}/resourceGroups/${var.environment}${var.stage}${components.terraform.azure-resource-group.vars.name}${var.namespace}/providers/Microsoft.Network/virtualNetworks/${var.environment}${var.stage}${components.terraform.azure-vnet.vars.name}${var.namespace}/subnets/${var.environment}${var.stage}${components.terraform.azure-subnet.vars.name}${var.namespace}"
    #     private_connection_resource_id: "/subscriptions/{subscription-id}/resourceGroups/{rg}/providers/Microsoft.KeyVault/vaults/{keyvault-name}"
    #     subresource_names: ["vault"]
    #     private_dns_zone_group:
    #       name: "keyvault-dns-zone-group"
    #       private_dns_zone_ids: ["/subscriptions/{subscription-id}/resourceGroups/{dns-rg}/providers/Microsoft.Network/privateDnsZones/privatelink.vaultcore.azure.net"]

    # Example 4: SQL Database Private Endpoint with Manual Approval
    # azure-private-endpoint-sql:
    #   metadata:
    #     component: azure-private-endpoint
    #   vars:
    #     name: "sqldb"
    #     location: "${var.location}"
    #     resource_group_name: "${var.environment}${var.stage}${components.terraform.azure-resource-group.vars.name}${var.namespace}"
    #     subnet_id: "/subscriptions/{subscription-id}/resourceGroups/${var.environment}${var.stage}${components.terraform.azure-resource-group.vars.name}${var.namespace}/providers/Microsoft.Network/virtualNetworks/${var.environment}${var.stage}${components.terraform.azure-vnet.vars.name}${var.namespace}/subnets/${var.environment}${var.stage}${components.terraform.azure-subnet.vars.name}${var.namespace}"
    #     private_connection_resource_id: "/subscriptions/{subscription-id}/resourceGroups/{rg}/providers/Microsoft.Sql/servers/{sql-server-name}"
    #     subresource_names: ["sqlServer"]
    #     is_manual_connection: true
    #     request_message: "Please approve private endpoint connection for development environment"
    #     private_dns_zone_group:
    #       name: "sql-dns-zone-group"
    #       private_dns_zone_ids: ["/subscriptions/{subscription-id}/resourceGroups/{dns-rg}/providers/Microsoft.Network/privateDnsZones/privatelink.database.windows.net"]

    # Example 5: Cosmos DB Private Endpoint with Custom IP Configuration
    # azure-private-endpoint-cosmos:
    #   metadata:
    #     component: azure-private-endpoint
    #   vars:
    #     name: "cosmos"
    #     location: "${var.location}"
    #     resource_group_name: "${var.environment}${var.stage}${components.terraform.azure-resource-group.vars.name}${var.namespace}"
    #     subnet_id: "/subscriptions/{subscription-id}/resourceGroups/${var.environment}${var.stage}${components.terraform.azure-resource-group.vars.name}${var.namespace}/providers/Microsoft.Network/virtualNetworks/${var.environment}${var.stage}${components.terraform.azure-vnet.vars.name}${var.namespace}/subnets/${var.environment}${var.stage}${components.terraform.azure-subnet.vars.name}${var.namespace}"
    #     private_connection_resource_id: "/subscriptions/{subscription-id}/resourceGroups/{rg}/providers/Microsoft.DocumentDB/databaseAccounts/{cosmos-account-name}"
    #     subresource_names: ["sql"]
    #     ip_configurations:
    #       - name: "cosmos-ip-config"
    #         private_ip_address: "10.0.1.100"
    #         subresource_name: "sql"
    #     private_dns_zone_group:
    #       name: "cosmos-dns-zone-group"
    #       private_dns_zone_ids: ["/subscriptions/{subscription-id}/resourceGroups/{dns-rg}/providers/Microsoft.Network/privateDnsZones/privatelink.documents.azure.com"]

    # =============================================================================
    # AZURE STORAGE ACCOUNT EXAMPLES
    # =============================================================================

    # Example 1: Standard V2 Storage Account with Blob and File Services
    azure-storage-account-general:
      vars:
        name: "general"
        location: "${var.location}"
        resource_group_name: "${var.environment}${var.stage}${components.terraform.azure-resource-group.vars.name}${var.namespace}"
        
        # Standard V2 configuration
        account_kind: "StorageV2"
        account_tier: "Standard"
        account_replication_type: "LRS"
        access_tier: "Hot"
        
        # Enable blob and file services
        enabled_services:
          - "blob"
          - "file"
        
        # Enable private endpoints for secure access
        create_private_endpoints: true
        private_endpoint_services:
          - "blob"
          - "file"
        private_endpoint_subnet_id: "/subscriptions/{subscription-id}/resourceGroups/${var.environment}${var.stage}${components.terraform.azure-resource-group.vars.name}${var.namespace}/providers/Microsoft.Network/virtualNetworks/${var.environment}${var.stage}${components.terraform.azure-vnet.vars.name}${var.namespace}/subnets/${var.environment}${var.stage}${components.terraform.azure-subnet.vars.name}${var.namespace}"
        
        # DNS zone groups for private endpoints
        private_endpoint_dns_zone_group_blob:
          name: "storage-blob-dns-zone-group"
          private_dns_zone_ids: ["/subscriptions/{subscription-id}/resourceGroups/{dns-rg}/providers/Microsoft.Network/privateDnsZones/privatelink.blob.core.windows.net"]
        
        private_endpoint_dns_zone_group_file:
          name: "storage-file-dns-zone-group"
          private_dns_zone_ids: ["/subscriptions/{subscription-id}/resourceGroups/{dns-rg}/providers/Microsoft.Network/privateDnsZones/privatelink.file.core.windows.net"]

    # Example 2: Data Lake Gen2 Storage Account
    # azure-storage-account-datalake:
    #   vars:
    #     name: "datalake"
    #     attributes: ["adls"]
    #     location: "${var.location}"
    #     resource_group_name: "${var.environment}${var.stage}${components.terraform.azure-resource-group.vars.name}${var.namespace}"
    #     
    #     # Data Lake Gen2 configuration
    #     account_kind: "StorageV2"
    #     account_tier: "Standard"
    #     account_replication_type: "GRS"
    #     is_hns_enabled: true  # Enable hierarchical namespace for Data Lake Gen2
    #     
    #     # Enable blob and dfs services for Data Lake
    #     enabled_services:
    #       - "blob"
    #     
    #     # Private endpoints for Data Lake services
    #     create_private_endpoints: true
    #     private_endpoint_services:
    #       - "blob"
    #       - "dfs"  # Data Lake File System endpoint
    #     private_endpoint_subnet_id: "/subscriptions/{subscription-id}/resourceGroups/${var.environment}${var.stage}${components.terraform.azure-resource-group.vars.name}${var.namespace}/providers/Microsoft.Network/virtualNetworks/${var.environment}${var.stage}${components.terraform.azure-vnet.vars.name}${var.namespace}/subnets/${var.environment}${var.stage}${components.terraform.azure-subnet.vars.name}${var.namespace}"
    #     
    #     # DNS zone groups for Data Lake endpoints
    #     private_endpoint_dns_zone_group_blob:
    #       name: "datalake-blob-dns-zone-group"
    #       private_dns_zone_ids: ["/subscriptions/{subscription-id}/resourceGroups/{dns-rg}/providers/Microsoft.Network/privateDnsZones/privatelink.blob.core.windows.net"]
    #     
    #     private_endpoint_dns_zone_group_dfs:
    #       name: "datalake-dfs-dns-zone-group"
    #       private_dns_zone_ids: ["/subscriptions/{subscription-id}/resourceGroups/{dns-rg}/providers/Microsoft.Network/privateDnsZones/privatelink.dfs.core.windows.net"]

    # Example 3: Premium Block Blob Storage (High Performance)
    # azure-storage-account-premium:
    #   vars:
    #     name: "premium"
    #     attributes: ["highperf"]
    #     location: "${var.location}"
    #     resource_group_name: "${var.environment}${var.stage}${components.terraform.azure-resource-group.vars.name}${var.namespace}"
    #     
    #     # Premium Block Blob Storage configuration
    #     account_kind: "BlockBlobStorage"
    #     account_tier: "Premium"
    #     account_replication_type: "LRS"
    #     
    #     # Only blob service for BlockBlobStorage
    #     enabled_services:
    #       - "blob"
    #     
    #     # Enhanced blob properties for premium storage
    #     blob_properties:
    #       versioning_enabled: true
    #       change_feed_enabled: true
    #       change_feed_retention_in_days: 30
    #       last_access_time_enabled: true
    #     
    #     # Private endpoint for premium blob storage
    #     create_private_endpoints: true
    #     private_endpoint_services:
    #       - "blob"
    #     private_endpoint_subnet_id: "/subscriptions/{subscription-id}/resourceGroups/${var.environment}${var.stage}${components.terraform.azure-resource-group.vars.name}${var.namespace}/providers/Microsoft.Network/virtualNetworks/${var.environment}${var.stage}${components.terraform.azure-vnet.vars.name}${var.namespace}/subnets/${var.environment}${var.stage}${components.terraform.azure-subnet.vars.name}${var.namespace}"

    # Example 4: Multi-Service Storage Account with All Services
    # azure-storage-account-multiservice:
    #   vars:
    #     name: "multiservice"
    #     location: "${var.location}"
    #     resource_group_name: "${var.environment}${var.stage}${components.terraform.azure-resource-group.vars.name}${var.namespace}"
    #     
    #     # Standard V2 with all services
    #     account_kind: "StorageV2"
    #     account_tier: "Standard"
    #     account_replication_type: "GRS"
    #     
    #     # Enable all storage services
    #     enabled_services:
    #       - "blob"
    #       - "file"
    #       - "queue"
    #       - "table"
    #     
    #     # Queue service configuration
    #     queue_properties:
    #       logging:
    #         delete: true
    #         read: true
    #         write: true
    #         version: "1.0"
    #         retention_policy_days: 7
    #     
    #     # File share configuration
    #     share_properties:
    #       retention_policy:
    #         days: 14
    #       smb:
    #         versions: ["SMB3.0", "SMB3.1.1"]
    #         authentication_types: ["NTLMv2", "Kerberos"]
    #     
    #     # Private endpoints for all services
    #     create_private_endpoints: true
    #     private_endpoint_services:
    #       - "blob"
    #       - "file"
    #       - "queue"
    #       - "table"
    #     private_endpoint_subnet_id: "/subscriptions/{subscription-id}/resourceGroups/${var.environment}${var.stage}${components.terraform.azure-resource-group.vars.name}${var.namespace}/providers/Microsoft.Network/virtualNetworks/${var.environment}${var.stage}${components.terraform.azure-vnet.vars.name}${var.namespace}/subnets/${var.environment}${var.stage}${components.terraform.azure-subnet.vars.name}${var.namespace}"
