components:
  terraform:
    azure-user-managed-identity:
      vars:
        # Development environment specific configuration
        tags:
          Purpose: "Development"
          CostCenter: "Engineering"