variable "enabled" {
  description = "Set to false to prevent the module from creating any resources"
  type        = bool
  default     = true
}

variable "location" {
  description = "The Azure Region where the private endpoint should be created"
  type        = string
}

variable "resource_group_name" {
  description = "The name of the resource group in which to create the private endpoint"
  type        = string
}

variable "subnet_id" {
  description = "The ID of the subnet from which the private IP will be allocated"
  type        = string
}

variable "private_endpoint_name" {
  description = "Custom name for the private endpoint. If not specified, the module will use the ID from the label module"
  type        = string
  default     = null
}

variable "private_service_connection_name" {
  description = "Custom name for the private service connection. If not specified, will use endpoint name with -psc suffix"
  type        = string
  default     = null
}

variable "private_connection_resource_id" {
  description = "The ID of the private link enabled remote resource"
  type        = string
}

variable "subresource_names" {
  description = "A list of subresource names which the private endpoint is able to connect to"
  type        = list(string)
  default     = []
}

variable "is_manual_connection" {
  description = "Does the private endpoint require manual approval from the remote resource owner?"
  type        = bool
  default     = false
}

variable "request_message" {
  description = "A message passed to the owner of the remote resource when the private endpoint attempts to establish the connection"
  type        = string
  default     = null
}

variable "private_dns_zone_group" {
  description = "A private DNS zone group block"
  type = object({
    name                 = string
    private_dns_zone_ids = list(string)
  })
  default = null
}

variable "ip_configurations" {
  description = "A list of IP configurations for the private endpoint"
  type = list(object({
    name               = string
    private_ip_address = string
    subresource_name   = optional(string)
    member_name        = optional(string)
  }))
  default = []
}

# Label module variables
variable "namespace" {
  description = "ID element. Usually an abbreviation of your organization name, e.g. 'eg' or 'cp', to help ensure generated IDs are globally unique"
  type        = string
  default     = null
}

variable "tenant" {
  description = "ID element _(Rarely used, not included by default)_. A customer identifier, indicating who this instance of a resource is for"
  type        = string
  default     = null
}

variable "environment" {
  description = "ID element. Usually used for region e.g. 'uw2', 'us-west-2', OR role 'prod', 'staging', 'dev', 'UAT'"
  type        = string
  default     = null
}

variable "stage" {
  description = "ID element. Usually used to indicate role, e.g. 'prod', 'staging', 'source', 'build', 'test', 'deploy', 'release'"
  type        = string
  default     = null
}

variable "name" {
  description = "ID element. Usually the component or solution name, e.g. 'app' or 'jenkins'"
  type        = string
  default     = null
}

variable "attributes" {
  description = "ID element. Additional attributes (e.g. `workers` or `cluster`) to add to `id` in the order they appear in the list"
  type        = list(string)
  default     = []
}

variable "delimiter" {
  description = "Delimiter to be used between ID elements"
  type        = string
  default     = "-"
}

variable "tags" {
  description = "Additional tags (e.g. `{'BusinessUnit': 'XYZ'}`)"
  type        = map(string)
  default     = {}
}

variable "regex_replace_chars" {
  description = "Terraform regular expression (regex) string. Characters matching the regex will be removed from the ID elements"
  type        = string
  default     = null
}

variable "label_order" {
  description = "The order in which the labels (ID elements) appear in the id"
  type        = list(string)
  default     = null
}

variable "label_key_case" {
  description = "Controls the letter case of the tags keys (label names) for tags generated by this module"
  type        = string
  default     = null
}

variable "label_value_case" {
  description = "Controls the letter case of the tags values for tags generated by this module"
  type        = string
  default     = null
}

variable "id_length_limit" {
  description = "Limit `id` to this many characters (minimum 6)"
  type        = number
  default     = null
}